# frozen_string_literal: true

# Gemfile
ruby '3.0.2'

source 'https://rubygems.org'

gem 'activerecord'
gem 'bcrypt', '~> 3.1.7'
gem 'puma'
gem 'rackup'
gem 'rake'
gem 'rubocop'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'simplecov'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.4'

group :test, :development do
  gem 'rack-test'
  gem 'rspec'
end
