# Gemfile
ruby '3.0.7'

source "https://rubygems.org"

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3', '~> 1.4'
gem 'rake'
gem 'rackup'
gem 'bcrypt', '~> 3.1.7'
gem 'simplecov'

group :test, :development do
  gem 'rspec'
  gem 'rack-test'
end